### ISSUE TITLE
FTS Setup

### ISSUE THREAD

**Issue by sysblade** [robertdebock/ansible-role-mssql#5]
I think it would be interesting to give the option to install the FTS engine for SQL Server.

For example we would have a `mssql_install_fts` or something like this, the only thing needed to execute is to install (Here in CentOS) the `mssql-server-fts` package.

**Comment by robertdebock** [comment]
Let me read and understand what FTS is, I'm not very microsoft aware...

Sounds like a good plan.

**Comment by sysblade** [comment]
I suppose the that should be doable for each roles of SQL Server, you have all the technical info there : https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-2017

About FTS, SQL Server Agent, integration services.

**Comment by robertdebock** [comment]
[Looks easy](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-full-text-search?view=sql-server-2017). I've prepared code and am testing it locally. Should be able to push and release today.

Thanks @kedare for a relevant contribution!

**Comment by robertdebock** [comment]
I'll close when tested and released. Probably tomorrow morning.

**Comment by robertdebock** [comment]
The tests and [release](https://galaxy.ansible.com/robertdebock/mssql) is done.

Please let me know if this works for you.

**Comment by sysblade** [comment]
Looks good to me :)
Thanks
